### ISSUE TITLE
Error handler <name>

### ISSUE THREAD

**Issue by romanmyko** [BelousSofiya/general-project#24]

**Comment by romanmyko** [comment]
This is a sample completion of the task
Dependency structure task
ua-1185-spacex-<name>-error.xml (ua-1185-spacex-api-error.xml)
├── Error handler (ua-1185-spacex-api-Error_Handler)
│   ├── Error Continue / Error Propagate
│   ├── code error: 404
│   └── Type error: HTTP: NOT_FOUND
| ua-1185-spacex-api-error.xml  | ua-1185-spacex-api-Error_Handler| Error Propagate  | 404 | HTTP: NOT_FOUND

**Comment by sophxmia** [comment]
HTTP Errors:


│ ├── Error Continue
│ ├── code error: 404
│ └── Type error: HTTP: NOT_FOUND

│ ├── Error Continue
│ ├── code error: 405
│ └── Type error: HTTP:METHOD_NOT_ALLOWED

APIKIT Errors:

│ ├── Error Propagate
│ ├── code error: 400
│ └── Type error: APIKIT:BAD_REQUEST

│ ├── Error Propagate
│ ├── code error: 404
│ └── Type error: APIKIT: NOT_FOUND

│ ├── Error Propagate
│ ├── code error: 405
│ └── Type error: APIKIT:METHOD_NOT_ALLOWED


I am not sure about this one 

│ ├── Error Propagate
│ ├── code error: 406
│ └── Type error:APIKIT:NOT_ACCEPTABLE

**Comment by sophxmia** [comment]
I believe this is the whole range of errors of the SpaceX project that we need now

**Comment by nasiisych** [comment]
ua-1185-mysql-system-error-handling.xml
│ ├── Error Continue 
│ ├── code error: 503
│ └── Type error: DB:CONNECTIVITY

│ ├── Error Continue 
│ ├── code error: 400
│ └── Type error: DB:BAD_SQL_SYNTAX

│ ├── Error Continue 
│ ├── code error: 400
│ └── Type error: DB:QUERY_EXECUTION

│ ├── Error Continue 
│ ├── code error: 422
│ └── Type error: VALIDATION:BLANK_STRING

│ ├── Error Continue 
│ ├── code error: 404
│ └── Type error: VALIDATION:EMPTY_COLLECTION

│ ├── Error Continue 
│ ├── code error: 500
│ └── Type error: EXPRESSION

│ ├── Error Continue 
│ ├── code error: 422
│ └── Type error: XML-MODULE:SCHEMA_NOT_HONOURED
